// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoAN9_gAODeqYri2PExKIm79DarugIdbQ',
    appId: '1:398811904033:web:3fd6fe6d6b88f0c0be4b60',
    messagingSenderId: '398811904033',
    projectId: 'noty-parents',
    authDomain: 'noty-parents.firebaseapp.com',
    storageBucket: 'noty-parents.firebasestorage.app',
    measurementId: 'G-0X0HJNFB25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwTpvLgE8R3bNDcuJ9wIhrByYLnsfr2ls',
    appId: '1:398811904033:android:60fc74f3720714b1be4b60',
    messagingSenderId: '398811904033',
    projectId: 'noty-parents',
    storageBucket: 'noty-parents.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0rVKH77CirN62Ebe4d0KUtnRR2qUG9zo',
    appId: '1:398811904033:ios:eb356c3e7e6f5e89be4b60',
    messagingSenderId: '398811904033',
    projectId: 'noty-parents',
    storageBucket: 'noty-parents.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0rVKH77CirN62Ebe4d0KUtnRR2qUG9zo',
    appId: '1:398811904033:ios:eb356c3e7e6f5e89be4b60',
    messagingSenderId: '398811904033',
    projectId: 'noty-parents',
    storageBucket: 'noty-parents.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoAN9_gAODeqYri2PExKIm79DarugIdbQ',
    appId: '1:398811904033:web:e9c9d516206bf9f6be4b60',
    messagingSenderId: '398811904033',
    projectId: 'noty-parents',
    authDomain: 'noty-parents.firebaseapp.com',
    storageBucket: 'noty-parents.firebasestorage.app',
    measurementId: 'G-N7GZ0M564T',
  );
}
